export const mockData = [
    {
        id: 1,
        question: 'What is the capital of France?',
        optA: 'New York',
        optB: 'London',
        optC: 'Paris',
        optD: 'Dublin',
        answer: 'c',
        archived: false,
    },
    {
        id: 2,
        question: 'Who is CEO of Tesla?',
        optA: 'Jeff Bezos',
        optB: 'Elon Musk',
        optC: 'Bill Gates',
        optD: 'Tony Stark',
        answer: 'b',
        archived: false,
    },
    {
        id: 3,
        question: 'The iPhone was created by which company?',
        optA: 'Apple',
        optB: 'Intel',
        optC: 'Amazon',
        optD: 'Microsoft',
        answer: 'a',
        archived: false,
    },
    {
        id: 4,
        question: 'How many Harry Potter books are there?',
        optA: '1',
        optB: '4',
        optC: '6',
        optD: '7',
        answer: 'd',
        archived: false,
    },
]